# Generated by Django 5.2.7 on 2025-10-30 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaRuido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_db', models.FloatField()),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
