# Generated by Django 5.2.8 on 2025-11-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruido_app', '0002_dispositivo_alter_lecturaruido_fecha_hora_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edificio',
            name='usuario',
        ),
    ]
