# Generated by Django 5.2.8 on 2025-11-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruido_app', '0003_remove_edificio_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturaruido',
            name='presencia',
            field=models.BooleanField(default=False),
        ),
    ]
